# Auto-generated by shift-clock's release workflow. Do not edit by hand.
class ShiftClock < Formula
  desc "Local, language-agnostic durable workflow orchestrator"
  homepage "https://github.com/phin-tech/shift-clock"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/phin-tech/shift-clock/releases/download/v0.1.0/shift-clock-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "fe665d1d06ce8f5f435839aa29ebb4795eb23230384bf5f27b3decf0bf236e1a"
    end
    # Intel-mac (x86_64) binary lands in the next release.
  end

  on_linux do
    on_arm do
      url "https://github.com/phin-tech/shift-clock/releases/download/v0.1.0/shift-clock-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "142c95e4db0b2f2ac405fb69e96c1fc72a17936f93b0dab5024dd950ddd87765"
    end
    on_intel do
      url "https://github.com/phin-tech/shift-clock/releases/download/v0.1.0/shift-clock-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "34c08fe4deea18b380f87e3d8fceb3893b52557f6630bc761c177a10728c4304"
    end
  end

  def install
    bin.install "shift-clock"
  end

  test do
    assert_match "shift-clock", shell_output("#{bin}/shift-clock --version")
  end
end
